---
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:

- name: amazon-2014.09.1
  driver_plugin: ec2
  driver_config:
    image_id: ami-b66ed3de
    region: us-east-1
    availability_zone: us-east-1b
    flavor_id: t2.micro
    username: ec2-user
    security_group_ids: <%= ENV['AWS_SECURITY_GROUP'] %>
    ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>

suites:
- name: default
  run_list:
  - recipe[gocd-server::default]
  attributes: {}